services:
  mosquitto:
    image: eclipse-mosquitto
    container_name:  mosquitto
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
      - ./certs:/mosquitto/certs

    ports:
      - 1883:1883
      - 9001:9001
      - 8883:8883

    stdin_open: true
    tty: true

    